#!/usr/bin/perl -w

#Interaction ID index for SNO+ from sngen:
$interaction{1} = "nu_e + e- --> nu_e + e-                         H2O ES";
$interaction{4} = "nu_e + 12C --> 12N + e-                          AV CC";
$interaction{5} = "nu_e + O --> F + e-                             H2O CC";
$interaction{7} = "nu_e + O --> F + e-                              AV CC";
$interaction{9} = "nu_e + 12C --> nu_e + 12C* (-> g)                AV NC";
$interaction{10} = "nu_e_bar + e- --> nu_e_bar + e-                H2O ES";
$interaction{12} = "nu_e_bar + p --> n + e+                        H2O CC";
$interaction{13} = "nu_e_bar + p --> n + e+                       H2O* CC";
$interaction{14} = "nu_e_bar + p --> n + e+                         AV CC";
$interaction{16} = "nu_e_bar + 12C --> 12B + e+                     AV CC";
$interaction{17} = "nu_e_bar + O --> N + e+                        H2O CC";
$interaction{20} = "nu_e_bar + 12C --> nu_e_bar + 12C* (-> g)       AV NC";
$interaction{21} = "nu_mu + e- --> nu_mu + e-                      H2O ES";
$interaction{24} = "nu_mu + 12C --> nu_mu + 12C* (-> g)             AV NC";
$interaction{26} = "nu_mu + 16O --> nu_mu + 15N + p + g            H2O NC";
$interaction{28} = "nu_mu + 16O --> nu_mu + 15O + n + g            H2O NC";
$interaction{30} = "nu_mu_bar + e- --> nu_mu_bar + e-              H2O ES";
$interaction{33} = "nu_mu_bar + 12C --> nu_mu_bar + 12C* (-> g)     AV NC";
$interaction{35} = "nu_mu_bar + 16O --> nu_mu_bar + 15N + p + g    H2O NC";
$interaction{37} = "nu_mu_bar + 16O --> nu_mu_bar + 15O + n + g    H2O NC";
$interaction{39} = "nu_tau + e- --> nu_tau + e-                    H2O ES";
$interaction{42} = "nu_tau + 12C --> nu_tau + 12C* (-> g)           AV NC";
$interaction{44} = "nu_tau + 16O --> nu_tau + 15N + p + g          H2O NC";
$interaction{46} = "nu_tau + 16O --> nu_tau + 15O + n + g          H2O NC";
$interaction{48} = "nu_tau_bar + e- --> nu_tau_bar + e-            H2O ES";
$interaction{51} = "nu_tau_bar + 12C --> nu_tau_bar + 12C* (-> g)   AV NC";
$interaction{53} = "nu_tau_bar + 16O --> nu_tau_bar + 15N + p + g  H2O NC";
$interaction{55} = "nu_tau_bar + 16O --> nu_tau_bar + 15O + n + g  H2O NC";
$interaction{57} = "nu_e + e- --> nu_e + e-                        LAB ES";
$interaction{58} = "nu_e + p  --> nu_e + p                         LAB ES";
$interaction{59} = "nu_e + 12C --> 12 N + e-                       LAB CC";
$interaction{60} = "nu_e + 12C --> nu_e + 12C* (-> g)              LAB NC";
$interaction{61} = "nu_e_bar + e- --> nu_e_bar + e-                LAB ES";
$interaction{62} = "nu_e_bar + p --> nu_e_bar + p                  LAB ES";
$interaction{63} = "nu_e_bar + p --> n + e+                        LAB CC";
$interaction{64} = "nu_e_bar + 12C --> 12B + e+                    LAB CC";
$interaction{65} = "nu_e_bar + 12C --> nu_e_bar + 12C* (-> g)      LAB NC";
$interaction{66} = "nu_mu + e- --> nu_mu + e-                      LAB ES";
$interaction{67} = "nu_mu + p --> nu_mu + p                        LAB ES";
$interaction{68} = "nu_mu + 12C --> nu_mu + 12C* (-> g)            LAB NC";
$interaction{69} = "nu_mu_bar + e- --> nu_mu_bar + e-              LAB ES";
$interaction{70} = "nu_mu_bar + p --> nu_mu_bar + p                LAB ES";
$interaction{71} = "nu_mu_bar + 12C --> nu_mu_bar + 12C* (-> g)    LAB NC";
$interaction{72} = "nu_tau + e- --> nu_tau + e-                    LAB ES";
$interaction{73} = "nu_tau + p --> nu_tau + p                      LAB ES";
$interaction{74} = "nu_tau + 12C --> nu_tau + 12C* (-> g)          LAB NC";
$interaction{75} = "nu_tau_bar + e- --> nu_tau_bar + e-            LAB ES";
$interaction{76} = "nu_tau_bar + p --> nu_tau_bar + p              LAB ES";
$interaction{77} = "nu_tau_bar + 12C --> nu_tau_bar + 12C* (-> g)  LAB NC";


#ID for this supernova simulation
$now = time;
$now_string = localtime(time);  
$host = `hostname`;
$user = `whoami`;
chop($user);
chop($host);

#Collect sngen output files and generate run_list.dat

$output = `mkdir sn_$now`;
print "making directory sn_$now:\n$output";

$output = `mv *.out sn_$now`;
print "moving *.out to sn_$now:\n$output";
 
$output = `mv snoman/new/*.out sn_$now`;
print "moving snoman/new/*.out to sn_$now:\n$output";

chdir "sn_$now";
print "changing directory to sn_$now/";

$output = `ls -1 mcpl*.out>run_list.dat`;
print "generating run_list.dat:\n$output"; 

#genearte RAT macro

open(RUN_LIST,"run_list.dat");
@runs = <RUN_LIST>;

$outfile = "sn_$now.mac";

open(OUT, ">$outfile");

printf OUT "#***************************************************** \n";
printf OUT "#*     Supernova RAT Macro \n";
printf OUT "#*	\n";
printf OUT "#*     This macro was generated by make_mcpl_macros.pl \n";
printf OUT "#*       from the output of sngen! \n";
printf OUT "#*	\n";
printf OUT "#*     Date:   $now_string	\n";
printf OUT "#*     User:   $user\@$host     \n";
printf OUT "#*	     \n";
printf OUT "#*     MonteCarlo Particle List Files: \n#*       ";
printf OUT join('#*       ',@runs) ;
printf OUT "#*\n";
printf OUT "#*****************************************************   \n";

printf OUT "\n";
printf OUT "/glg4debug/glg4param omit_muon_processes  0.0 \n";
printf OUT "/glg4debug/glg4param omit_hadronic_processes  0.0 \n";

printf OUT "\n";
printf OUT "/rat/db/set DETECTOR geo_file \"geo/snoplus.geo\" \n";

printf OUT "\n";
printf OUT "/rat/db/set DAQ n100_hi_thresh 20.0     \n";
printf OUT "/rat/db/set DAQ n100_med_thresh 18.0     \n";
printf OUT "/rat/db/set DAQ n100_lo_thresh 16.0     \n";
printf OUT "/rat/db/set DAQ n20_thresh 20.0     \n";
printf OUT "/rat/db/set DAQ n20_lb_thresh 20.0     \n";
printf OUT "/rat/db/set DAQ eshi_thresh 160.0     \n";
printf OUT "/rat/db/set DAQ eslo_thresh 120.0     \n";
printf OUT "/rat/db/set NOISE noise_flag 1     \n";
printf OUT "/rat/db/set NOISE noise_rate 500.0d        \n";

printf OUT "\n";
printf OUT "/run/initialize \n";

printf OUT "\n";
printf OUT "/rat/proc frontend \n";
printf OUT "/rat/proc trigger \n";
printf OUT "/rat/proc eventbuilder \n";

printf OUT "\n";
printf OUT "/rat/proc count \n";
printf OUT "/rat/procset update 10 \n";

printf OUT "\n";
printf OUT "/rat/proclast outroot \n";
printf OUT "/rat/procset file \"sn_$now.root\" \n";
printf OUT "\n";
printf OUT "\n";


foreach $run(@runs) {

    print "working on run ",$run, "\n";

    open(MCPL,"<$run");
    
    $line = 0;
    while(<MCPL>){
	if($line > 32)
	{
	    ($num, $id, $x, $y, $z, $t, $e, $px, $py, $pz) = split;
	    $num = $num;  #just so you dont get a warning ;
	    if ($id == 20){
		$id2 = "e-";
	    }
	    if ($id == 81){
		$id2 = "neutron";
	    }
	    if ($id == 80){
		$id2 = "proton";
	    }
	    if ($id == 2){
		$id2 = "gamma";
	    }
	   
	    printf OUT "/generator/add combo gun3:point \n";
	    printf OUT "/generator/pos/set $x $y $z \n";
	    printf OUT "/generator/vtx/set $id2 $px $py $pz $e $t \n";
	    printf OUT "/generator/rate/set 1 \n";
	    printf OUT "/rat/run/start 1\n";
	    
	    printf OUT "\n";
	    printf OUT "\n";
	}
	$line++;
    }
}
printf OUT "exit\n";


