**************************************************************************
*  Filename: aspline_size.inc
**************************************************************************

      INTEGER aspline_size

* largest data set that needs to be spline fit

c      PARAMETER (aspline_size = 126)   ! deuterium cross section data
c      PARAMETER (aspline_size = 460)   ! Bruenn 15 Ms lum/en data
c      PARAMETER (aspline_size = 999)   ! Bruenn 25 Ms lum/en data
      PARAMETER (aspline_size = 1700)   ! ES radiative correction xsect data
