*FILE MEMBER=DB_MISC LIBRARY=SNODB LANGUAGE=INC DATE=16:Jul:1995
 
*     SNODB:  miscellaneous declarations for database tools
 
*     Contact:  R. Komar (UBC)
*               D. Cowen (UPenn)
 
*     Revision History:-
*     ================
 
*     2.09  R. Komar     First version
 
 
*     Variables:-
*     =========
 
	integer isnodiv
	integer lsno
	common /snolnk/ isnodiv,lsno
	integer irc
 
*ENDFILE MEMBER=DB_MISC
