*****************************************************************************
*  Filename: id_int.inc
*****************************************************************************
*
*  Assign SNOMAN id energy codes to the different interaction classes
*
*****************************************************************************

      INTEGER id_nu_cc, id_nu_nc, id_nu_es 

      PARAMETER (id_nu_cc = 20)
      PARAMETER (id_nu_nc = 30)
      PARAMETER (id_nu_es = 40)
 
