***************************************************************************
*  Filename: id_nu.inc
***************************************************************************
*
*  Assign SNOMAN neutrino particle id codes
*
***************************************************************************

      INTEGER id_nu_e, id_nu_ebar, 
     +        id_nu_mu, id_nu_mubar, 
     +        id_nu_tau, id_nu_taubar

      PARAMETER (id_nu_e = 30)
      PARAMETER (id_nu_ebar = 31)
      PARAMETER (id_nu_mu = 32)
      PARAMETER (id_nu_mubar = 33)
      PARAMETER (id_nu_tau = 34)
      PARAMETER (id_nu_taubar = 35)

 
