      INTEGER es_size_SNO, cc_size_SNO, nc_size_SNO
      INTEGER es_size_SNOP, cc_size_SNOP, nc_size_SNOP
      INTEGER es_size_HALO, cc_size_HALO, nc_size_HALO

      PARAMETER (es_size_SNO = 12)
      PARAMETER (cc_size_SNO = 12)
      PARAMETER (nc_size_SNO = 32)
      PARAMETER (es_size_SNOP = 18)
      PARAMETER (cc_size_SNOP = 10)
      PARAMETER (nc_size_SNOP = 20)
      PARAMETER (es_size_HALO = 6)
      PARAMETER (cc_size_HALO = 4)
      PARAMETER (nc_size_HALO = 12)

