      INTEGER nu_e_size_SNO, nu_eb_size_SNO, 
     +        nu_mu_size_SNO, nu_mub_size_SNO,
     +        nu_tau_size_SNO, nu_taub_size_SNO,
     +        nu_e_size_SNOP, nu_eb_size_SNOP,
     +        nu_mu_size_SNOP, nu_mub_size_SNOP,
     +        nu_tau_size_SNOP, nu_taub_size_SNOP,
     +        nu_e_size_HALO, nu_eb_size_HALO,
     +        nu_mu_size_HALO, nu_mub_size_HALO,
     +        nu_tau_size_HALO, nu_taub_size_HALO

      PARAMETER (nu_e_size_SNO = 9)
      PARAMETER (nu_eb_size_SNO = 11)
      PARAMETER (nu_mu_size_SNO = 9)
      PARAMETER (nu_mub_size_SNO = 9)
      PARAMETER (nu_tau_size_SNO = 9)
      PARAMETER (nu_taub_size_SNO = 9)

      PARAMETER (nu_e_size_SNOP = 9)
      PARAMETER (nu_eb_size_SNOP = 12)
      PARAMETER (nu_mu_size_SNOP = 7)
      PARAMETER (nu_mub_size_SNOP = 7)
      PARAMETER (nu_tau_size_SNOP = 7)
      PARAMETER (nu_taub_size_SNOP = 7)

      PARAMETER (nu_e_size_HALO = 5)
      PARAMETER (nu_eb_size_HALO = 5)
      PARAMETER (nu_mu_size_HALO = 3)
      PARAMETER (nu_mub_size_HALO = 3)
      PARAMETER (nu_tau_size_HALO = 3)
      PARAMETER (nu_taub_size_HALO = 3)



