************************************************************************
*  Filename: random_seed.inc
************************************************************************
*
*  Specifies the random seeds used for the various independent data sets
*
*************************************************************************

      INTEGER iseed

* v1
*      PARAMETER (iseed = -14141)
* v2
      PARAMETER (iseed = -82837)
* v3
*      PARAMETER (iseed = -50329)  ! may hang
* v4
*      PARAMETER (iseed = -132516)
* v5 (gives problem with BV 50000)
*      PARAMETER (iseed = -615321)
* v6
*      PARAMETER (iseed = -531261)
* v7
*      PARAMETER (iseed = -66258)
* v8
*      PARAMETER (iseed = -62301)
* v9
*      PARAMETER (iseed = -124602)
* v10
*      PARAMETER (iseed = -20602)
* v11
*      PARAMETER (iseed = -91101)
