***************************************************************************
*  Filename: xsect_size.inc
***************************************************************************
*
*  This file specifies the number of cross section entries in the various
*  data files
*
****************************************************************************


      INTEGER xs_nu_d_entries,
     +        xs_nu_e_entries,
     +        xs_nu_12C_entries,
     +        xs_nu_12C_Paar_entries,
     +        xs_nu_O_entries,
     +        xs_nu_16O_Paar_entries,
     +        xs_nu_208Pb_nc_entries,
     +        xs_nu_208Pb_cc_entries,
     +        xs_nu_208Pb_cc_Engel_1n_entries,
     +        xs_nu_208Pb_cc_Engel_2n_entries,
     +        xs_nu_208Pb_nc_Engel_1n_entries,
     +        xs_nu_208Pb_nc_Engel_2n_entries

      PARAMETER (xs_nu_d_entries = 136)
      PARAMETER (xs_nu_e_entries = 1700)
      PARAMETER (xs_nu_12C_entries = 19)
      PARAMETER (xs_nu_12C_Paar_entries = 34)
      PARAMETER (xs_nu_O_entries = 24)
      PARAMETER (xs_nu_16O_Paar_entries = 41)
      PARAMETER (xs_nu_208Pb_nc_entries = 29)
      PARAMETER (xs_nu_208Pb_cc_entries = 29)
      PARAMETER (xs_nu_208Pb_cc_Engel_1n_entries = 18)
      PARAMETER (xs_nu_208Pb_cc_Engel_2n_entries = 15)
      PARAMETER (xs_nu_208Pb_nc_Engel_1n_entries = 18)
      PARAMETER (xs_nu_208Pb_nc_Engel_2n_entries = 15)



